run:
  deadline: 10m

  skip-dirs:
    - implementations/mocksqldb

linters:
  enable-all: true
  disable:
    - dupl
    - goconst
    - gocyclo
    - depguard
    - lll
    - gochecknoglobals

linters-settings:
  govet:
    check-shadowing: true

  maligned:
    suggest-new: true

  misspell:
    locale: US

  prealloc:
    for-loops: true

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      # diagnostic
      - argOrder
      - sloppyReassign
      # style
      #performance

issues:
  max-same-issues: 0
  max-per-linter: 0
  exclude-use-default: false

  exclude-rules:
    - linters:
        - gosec
      text: 'G304'
